# -*- coding: utf-8 -*-
"""llm_decision_maker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSj1kK0reoQLfeDpHAHw-bBIIoy8A5OD

## New Step
"""


from datetime import datetime
import pandas as pd
import numpy as np
from datetime import timedelta
import requests
from langchain_ollama import ChatOllama
import json
import time
import os

from module_llm_helper import *
from module_llm_prompts import *
from mtd_utils import HostIPQueueManager, RouteHistoryManager, all_hosts


# llm1 llm2 replacement
from module_static_function import code_filter_hosts, code_filter_links

# ===================== CELL 1: build HOST-focused scene + store what will be shown to LLM =====================
HOST_CSV = "host_stats_onos.csv"          # <-- your host stats CSV
HOST_META = "host_metadata.json"    # <-- optional (mac->host mapping)
WINDOW_MINUTES = 5
TREND_POINTS = 10
SCENE_LOG = "llm_scene_log.jsonl"
DECISION_LOG = "llm_decision_log.jsonl"

CLOUD_URL = "https://ollama.com/api/chat"
API_KEY = "23fbf0f676584a7983158ded37540f2c.9C4Aw8pI8jXQlC1vDCGIF7nb"
MODEL_NAME = "gpt-oss:20b-cloud"

LINK_CSV = "link_stats_onos.csv"
EXAMPLES_JSONL = "examples.jsonl"


HOST_CSV = "host_stats_onos.csv"
LINK_CSV = "link_stats_onos.csv"
EXAMPLES_JSONL = "examples.jsonl"

# ---------------- INIT ONCE ----------------
ip_manager = HostIPQueueManager()

route_manager = RouteHistoryManager(all_hosts, queue_size=10)
route_manager.load_from_csv()

for i in range(1, 41):
    ip_manager.set_host_ips(f"h{i}", [i])

ip_manager.load_from_csv()

# ---------------- LOOP ----------------
while True:
    #commenting for static replacement
    # # -------- HOST --------
    # scene, prompt = build_host_scene_and_prompt()
    # # out, latency = call_cloud_llm(prompt)
    # out, latency = json_check(prompt)

    # print(out)
    # print("Latency for Host:", latency)


    # # -------- LINK --------
    # scene2, prompt2, decision_ts = build_link_scene_and_prompt()
    # # out2, latency2 = call_cloud_llm(prompt2)
    # out2, latency2 = json_check(prompt2)

    # print(out2)
    # print("Latency for Links:", latency2)
    #commenting for static replacement

    # -------- HOST --------
    scene, prompt = build_host_scene_and_prompt()
    out, flagged_macs = code_filter_hosts(scene["host_stats"])

    # print("out:", out) #commented for report
    print("\nFlagged Hosts:", flagged_macs)


    # -------- LINK --------
    scene2, prompt2, decision_ts = build_link_scene_and_prompt()
    out2, flagged_links = code_filter_links(scene2["link_stats"])

    # print("out2:", out2) #commented for report
    print("\nFlagged Links:", flagged_links)


    # -------- FLAGGED --------
    host_report, link_report, flagged_macs, flagged_links, flagged_host_stats, flagged_link_stats = \
        get_flagged_entities_with_trends(out, out2)

    fusion_scene = {
        # "host_report": host_report,
        # "link_report": link_report, #newly commented
        "flagged_host_stats": flagged_host_stats,
        "flagged_link_stats": flagged_link_stats,
        # "policy_order": ["do_nothing", "rrm", "ip", "both"]
        "policy_order": ["do_nothing", "rrm", "ip"]

    }




    # -------- HISTORY SUMMARY --------
    history_summary = build_llm_history_summary(EXAMPLES_JSONL, n=5)
    # history_summary=""
    ## -------- FINAL DECISION --------
    ## final_prompt = build_final_prompt(fusion_scene)   # from prompt module
    # -------- FINAL DECISION --------
    final_prompt = build_final_prompt(fusion_scene, history_summary)

    # print(final_prompt)
    # final_out, final_latency = call_gemini(final_prompt)
    # final_out, final_latency = call_cloud_llm(final_prompt)

    final_out, final_latency = json_check(final_prompt)
    final_obj = json.loads(final_out)

    # print(history_summary) #temp

    # final_obj = json.loads(final_out)

    print("\nLLM Response:", json.dumps(final_obj, indent=2))
    print("Latency:", final_latency)


    # -------- PATH SELECTION --------
    candidates = path_selector(final_obj, "hop_list.csv")

    for c in candidates:
        print(c)


    # -------- DISPATCH --------
    ip_result, route_result = dispatch_mitigation(
        final_obj,
        "hop_list.csv",
        ip_manager,
        route_manager
    )


    # -------- VALIDATION --------
    validation_out = validate_effect(fusion_scene, final_obj, decision_ts)


    # -------- SAVE --------
    example = make_example(
        fusion_scene,
        final_obj,
        validation_out,
        ip_result,
        route_result
    )

    save_example(example)

    #simple print 
    outcome = example.get("outcome", {})
    act = example.get("mtd_action", {})

    print(
        f"[RESULT] {outcome.get('label')} | "
        f"score={outcome.get('score'):.3f} | "
        f"sel={outcome.get('selected_score'):.3f} | "
        f"other={outcome.get('other_candidate_score'):.3f} | "
        f"ip={act.get('ip_changes')} | "
        f"route={act.get('route_changes')}"
    )

    # print("\ndone sleeping for 10s") #removed June 2026
    # time.sleep(10)